// Autogenerated from Pigeon (v3.2.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface Model ()
+ (Model *)fromMap:(NSDictionary *)dict;
+ (nullable Model *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation Model
+ (instancetype)makeWithId:(NSNumber *)id
    title:(NSString *)title {
  Model* pigeonResult = [[Model alloc] init];
  pigeonResult.id = id;
  pigeonResult.title = title;
  return pigeonResult;
}
+ (Model *)fromMap:(NSDictionary *)dict {
  Model *pigeonResult = [[Model alloc] init];
  pigeonResult.id = GetNullableObject(dict, @"id");
  NSAssert(pigeonResult.id != nil, @"");
  pigeonResult.title = GetNullableObject(dict, @"title");
  NSAssert(pigeonResult.title != nil, @"");
  return pigeonResult;
}
+ (nullable Model *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [Model fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"id" : (self.id ?: [NSNull null]),
    @"title" : (self.title ?: [NSNull null]),
  };
}
@end

@interface ModelApiCodecReader : FlutterStandardReader
@end
@implementation ModelApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [Model fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface ModelApiCodecWriter : FlutterStandardWriter
@end
@implementation ModelApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[Model class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface ModelApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation ModelApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[ModelApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[ModelApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *ModelApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    ModelApiCodecReaderWriter *readerWriter = [[ModelApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void ModelApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ModelApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ModelApi.getModel"
        binaryMessenger:binaryMessenger
        codec:ModelApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getModelId:error:)], @"ModelApi api (%@) doesn't respond to @selector(getModelId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_id = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        Model *output = [api getModelId:arg_id error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
